# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  PRJ_VENV_NAME: site-yairdar-com-cvenv

includes:
  docs-builder: taskfiles/mkdocs-basic-pack/mkdocs-build-basic.tasks.yml
  venv:
    taskfile: ./taskfiles/conda-venv.tasks.yaml
    vars:
      VENV_NAME: '{{.PRJ_VENV_NAME}}'

tasks: 
  
  default:
    cmds: [{task: info}]
  
  info:
    desc: Info
    silent: true
    cmds: [task -l]

  spin:exec:
    desc: spinup deck
    cmds:
      - task {{.TASK}} -d {{.deck}} cmd={{.cmd}}

  spin:up:
    desc: spinup deck
    cmds:
      - task {{.TASK}} -d {{.deck}}

  mkdocs:build:
    desc: _
    cmds:
      - task docs-builder:build-docs

  