# https://taskfile.dev

version: '3'

includes:
  deps: ./tasks/deps.tasks.yaml

vars:
  _name_: aguide dir api

tasks:
  default:
    cmds:
      - echo "{{._name_}}"
      - task -l
    silent: true

