# https://taskfile.dev

version: '3'

includes:
  deps: ./tasks/deps.tasks.yaml
  docs-builder: _infra/mkdocs-basic-pack/mkdocs-build-basic.tasks.yml
  reposet: _infra/reposet_pack/reposet.tasks.yml
  docs-publisher: tasks/mkdocs-publish.tasks.yml

vars:
  _name_: aguide dir api
  source_root: "$(realpath .)"
  reposet__conf_map: relrepos:_layout_/reposet.conf_v4.yaml@vars.reposet_items_yaml
  
tasks:
  default:
    cmds:
      - echo "{{._name_}}"
      - task -l
    silent: true

  spin:up:
    desc: spinup deck
    cmds:
      - task {{.TASK}} -d {{.deck}}

  spin:exec:
    desc: spinup deck
    cmds:
      - task {{.TASK}} -d {{.deck}} cmd={{.cmd}}

  mkdocs:build:
    desc: _
    cmds:
      - task spin:exec deck=decks/mkdocs-live cmd='"mkdocs build"'
