jobs:

  a-task-tutorial/c01_getting_started: 
    props: &ref_tut_entry
      # active: true
      job_type: pipelineJob
      description: "desc: task runner job"
      git_url: "https://github.com/yairdar/aguide.git"
      jenkins_pipeline_path: "_cicd/job_from_taskfile_pipe.groovy"
      branch: "*/main"
      # cred_id: guthub-token--jenkins-bot
      params: &ref_tut_params
      - { name: entrypoint_task, value: ci-flow, desc: select entrypoint taskname, usually ci-flow}
      - { name: taskfile_path, value: Taskfile.yaml, desc: select taskfile name}
      envvars:
      - { name: taskwork_dir, value: docs/base-tutorials/a-tasker/c01_getting_started, desc: ""}

  a-task-tutorial/c02_task_directory:
    props:
      <<: *ref_tut_entry
      envvars:
      - { name: taskwork_dir, value: docs/base-tutorials/a-tasker/c02_task_directory, desc: ""}

  a-task-tutorial/c03_including_taskfiles:
    props:
      <<: *ref_tut_entry
      envvars:
      - { name: taskwork_dir, value: docs/base-tutorials/a-tasker/c03_including_taskfiles, desc: ""}

