# to create a Taskfile.yaml in a dircetory, run task -i or task --init
# https://taskfile.dev

version: '3'

vars:
  GREETING: |-
    'By default the task runs in the same dircetory where the Taskfile is located,
    but for any task you can specify a dircetory where to run it.'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  new-text-file:
    desc: make a new text file inside a new directory
    dir: temp 
    cmds:
      - echo "That's how task directories work" > thats_how.txt

  read-text:
    desc: read the text file from a subdirectory
    dir: temp
    cmds:
      - cat thats_how.txt 

  cleanup:
    desc: remove a subdirectory so you can start from scratch
    cmds:
      - rm -r temp
