# to create a Taskfile.yaml in a dircetory, run task -i or task --init
# https://taskfile.dev

version: '3'

vars:
  GREETING: 'Try to run one task, then two tasks together like this: task greet get-started'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  first-task:
    desc: _
    cmds:
      - echo "My first task runs fine"
  
  get-started:
    desc: _
    cmds:
      - echo "Call any task to get started"

  
  calling-tasks:
    desc: one task can call another tasks, like this one does
    cmds:
      - task: get-started
      - task: first-task

  ### === API part for autorun automation ===
  ### --- Run Tutorial ---

  run-all-in-seq:
    desc: run all tasks in sequence
    cmds:
    - task first-task
    - task get-started
    - task calling-tasks

  run-all-in-par:
    desc: run all tasks in sequence
    deps:
    - first-task
    - get-started
    - calling-tasks

  ### --- Main Ci-Flow ---

  ci-flow:
    desc: ci-flow for this project
    cmds:
    - task run-all-in-par
    - task run-all-in-seq

