# https://taskfile.dev

version: '3'

vars:
  _name_: sbin:yd.dir.api

tasks:
  default:
    cmds:
      - echo "{{._name_}}"
      - task -l
    silent: true

  
  symlink:ydman:
    desc: create a symlink for ydman task tool
    vars: 
      apdest: ydman
      apsource: ../_infra/ydman_lib/ydman.exe.yml
      apcmd: ln -s --force ${apsource} ${apdest}
    env:
      apsource: '{{.apsource}}'
      apdest: '{{.apdest}}'
    cmds:
      - echo "[DBG:info][${apsource} ${apdest}]" >&2
      - |
        {{.apcmd}}
      - chmod +x {{.apdest}}
    status:
      - |
        [[ ! -e {{.apdest}} ]]

  symlink:ydbase:
    desc: create a symlink for ydman task tool
    vars: 
      apdest: ydbase
      apsource: ./vparts/ydbase.vpart.tskr.yml
      apcmd: ln -s --force ${apsource} ${apdest}
    env:
      apsource: '{{.apsource}}'
      apdest: '{{.apdest}}'
    cmds:
      - echo "[DBG:info][${apsource} ${apdest}]" >&2
      - |
        {{.apcmd}}
      - chmod +x {{.apdest}}
    status:
      - |
        [[ ! -e {{.apdest}} ]]