# https://taskfile.dev

version: '3'

includes:
  from-another-file:
    taskfile: greet.tasks.yaml
  from-subdir: ./greet_dir
  from-nonexisting-file:
    taskfile: taskfile.thats.not.there.yaml
    optional: true

vars:
  GREETING: Here we include an external taskfile and even a folder

tasks:
  default:
    desc: See, there's only one default task in this file.
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true
