#!/usr/local/bin/task --taskfile

# https://taskfile.dev

version: '3'

vars:
  _name_: genv.asdf.tasks.yaml
  _kind_: ydk:tskr.exe/tasker

tasks:
  install:asdf:tool:
    preconditions:
      - sh: "[ ! -z  '{{._os_deps}}' ]"
        msg: "expected args"
    vars:
      _args: |-
        _os_deps: curl git unzip
        _tool: rclone
        _version_exp: rclone version
    
    cmds:
      - sudo apt install -y {{._os_deps}}
      - asdf plugin-add {{._tool}} || true
      - asdf plugin-add {{._tool}} |& grep 'Plugin named {{._tool}} already added'
      - asdf install {{._tool}} latest
      - asdf global {{._tool}} $(asdf latest {{._tool}})
      - echo $({{._version_exp}}) 
    status:
      - |-
        {{._version_exp}}
        echo ".@@=dict: status=present tool={{._tool}} version=$({{._version_exp}})" >> /dev/stderr

  install:rclone:
    vars:
      _os_deps: curl git unzip
      _tool: rclone
      _version_exp: rclone version
    cmds:
      - sudo apt install -y {{._os_deps}}
      - asdf plugin-add {{._tool}} || true
      - asdf plugin-add {{._tool}} |& grep 'Plugin named {{._tool}} already added'
      - asdf install {{._tool}} latest
      - asdf global {{._tool}} $(asdf latest {{._tool}})
      - echo $({{._version_exp}}) 
    status:
      - |-
        {{._version_exp}}
        echo ".@@=dict: status=present tool={{._tool}}" >> /dev/stderr

#asdf plugin-add task https://github.com/particledecay/asdf-task.git