
name: ci-flow

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install pip.deps
        run: task docs-builder:install-pip-deps

      - name: task mkdocs:build
        run: task mkdocs:build

      - uses: actions/checkout@v3
        with:
          repository: yairdar/yairdar.github.io
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github@example.com"
      
      - name: republish on local channel
        run: task docs-publisher:prepublish-to-local-upstream

      - name: push to remote
        run: task docs-publisher:publish-local-upstream-to-remote

      # - run: git push origin master
      
      # - name: checkout

